# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
ar = np.array([0, 1, 2, 3, 4 , 5, 6, 7, 8, 9])
ar = ar.reshape((2,5))
print(ar)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [3]:
ar1 = np.array([[0, 1, 2, 3, 4],
                [5, 6, 7, 8, 9]])
ar2 = np.ones((2,5))
ar3 = np.vstack((ar1,ar2))
ar3.astype('int32')

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [5]:
arr4 = np.hstack((ar1,ar2))
arr4.astype('int32')

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [7]:
ar.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [8]:
ar5 = np.array([
    [ 0, 1, 2],
    [ 3, 4, 5],
    [ 6, 7, 8],
    [ 9, 10, 11],
    [12, 13, 14]
])
np.ravel(ar5)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [9]:
ar5.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [12]:
ar6 = np.random.randint(1,25, size = (5,5))
print("Original: \n")
print (ar6)
print("\n")
print("Square of Array: \n")
print(ar6 ** 2)

Original: 

[[ 2 10  9  4 22]
 [21 11  1 20 15]
 [14 15 10 20  5]
 [23 13 15  7  9]
 [23 14  4 24  8]]


Square of Array: 

[[  4 100  81  16 484]
 [441 121   1 400 225]
 [196 225 100 400  25]
 [529 169 225  49  81]
 [529 196  16 576  64]]


## Question:8

### Create 5x6 an array and find the mean?

In [13]:
ar8 = np.random.randint(1,20, size = (5,6))
print("Original: \n")
print (ar8)
print("\n")
print("Mean of Array: \n")
print(ar8.mean())

Original: 

[[ 1 18 17  5  8 18]
 [ 7  7 13  1  2  6]
 [ 8  5 17 12  2  5]
 [ 3 14  1 11  6  9]
 [ 7  1  3  8 10  5]]


Mean of Array: 

7.666666666666667


## Question:9

### Find the standard deviation of the previous array in Q8?

In [14]:
print("Original: \n")
print (ar8)
print("\n")
print("Standard deviation of Array: \n")
print(np.std(ar8))

Original: 

[[ 1 18 17  5  8 18]
 [ 7  7 13  1  2  6]
 [ 8  5 17 12  2  5]
 [ 3 14  1 11  6  9]
 [ 7  1  3  8 10  5]]


Standard deviation of Array: 

5.211099265563414


## Question:10

### Find the median of the previous array in Q8?

In [15]:
print("Original: \n")
print (ar8)
print("\n")
print("Median of Array: \n")
print(np.median(ar8))

Original: 

[[ 1 18 17  5  8 18]
 [ 7  7 13  1  2  6]
 [ 8  5 17 12  2  5]
 [ 3 14  1 11  6  9]
 [ 7  1  3  8 10  5]]


Median of Array: 

7.0


## Question:11

### Find the transpose of the previous array in Q8?

In [16]:
print("Original: \n")
print (ar8)
print("\n")
print("Transpose of Array: \n")
print(np.transpose(ar8))

Original: 

[[ 1 18 17  5  8 18]
 [ 7  7 13  1  2  6]
 [ 8  5 17 12  2  5]
 [ 3 14  1 11  6  9]
 [ 7  1  3  8 10  5]]


Transpose of Array: 

[[ 1  7  8  3  7]
 [18  7  5 14  1]
 [17 13 17  1  3]
 [ 5  1 12 11  8]
 [ 8  2  2  6 10]
 [18  6  5  9  5]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [18]:
ar7 = np.random.randint(1,20, size = (4,4))
print("Original: \n")
print (ar7)
print("\n")
print("Sum of diagonal elements of Array: \n")
np.trace(ar7)

Original: 

[[13  8 10  5]
 [ 8  2 11  8]
 [ 3  3  3 14]
 [12 11  9  6]]


Sum of diagonal elements of Array: 



24

## Question:13

### Find the determinant of the previous array in Q12?

In [19]:
print("Original: \n")
print (ar7)
print("\n")
print("Determinant: \n")
np.linalg.det(ar7)

Original: 

[[13  8 10  5]
 [ 8  2 11  8]
 [ 3  3  3 14]
 [12 11  9  6]]


Determinant: 



2498.9999999999973

## Question:14

### Find the 5th and 95th percentile of an array?

In [20]:
print("Original: \n")
print (ar7)
print("\n")
print(f"5th percentile of an array: {np.percentile(ar7, 5)}")
print(f"95th percentile of an array: {np.percentile(ar7, 95)}")

Original: 

[[13  8 10  5]
 [ 8  2 11  8]
 [ 3  3  3 14]
 [12 11  9  6]]


5th percentile of an array: 2.75
95th percentile of an array: 13.25


## Question:15

### How to find if a given array has any null values?

In [23]:
np.isnan(arr6).any()

False