# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
arry = np.zeros((10))

3. Create a vector with values ranging from 10 to 49

In [3]:
arry_rng = np.arange(10,49)

4. Find the shape of previous array in question 3

In [4]:
arry_rng.shape

(39,)

5. Print the type of the previous array in question 3

In [5]:
arry_rng.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [7]:
print(np.__version__)
print(np.show_config())

1.16.5
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Anaconda\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Anaconda\\Library\\include']
blas

7. Print the dimension of the array in question 3


In [8]:
print(arry_rng.ndim)

1


8. Create a boolean array with all the True values

In [9]:
boolean = np.ones((10),dtype=bool)

9. Create a two dimensional array




In [11]:
twoD = np.zeros((10,10))
print(twoD.ndim)

2


10. Create a three dimensional array



In [12]:
threed = np.zeros((10,10,10))
print(threed.ndim)

3


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [13]:
reverse = np.random.randn((10))
print(reverse)
reverse = np.flip(reverse)
print(reverse)

[ 0.47628221  1.25078758 -1.05947427  0.16450208 -0.24804935 -1.72621987
  0.88489746  0.93306538 -0.79304734 -0.17717015]
[-0.17717015 -0.79304734  0.93306538  0.88489746 -1.72621987 -0.24804935
  0.16450208 -1.05947427  1.25078758  0.47628221]


12. Create a null vector of size 10 but the fifth value which is 1 

In [14]:
nullV = np.array([1 if x == 4 else 0 for x in range(10)])
print(nullV)

[0 0 0 0 1 0 0 0 0 0]


13. Create a 3x3 identity matrix

In [15]:
identity = np.identity(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [16]:
arr = np.array([1,2,3,4,5],dtype=float)
arr.dtype

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [17]:
ar1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
ar2 = np.array([[0., 4., 1.],[7., 2., 12.]])
ar1 * ar2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [18]:
ar1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
ar2 = np.array([[0., 4., 1.],[7., 2., 12.]])
ar3 = ar1 == ar2
print(ar3)

[[False False False]
 [False False False]]


17. Extract all odd numbers from arr with values(0-9)

In [19]:
odd = np.arange(0,10)
print(odd[odd % 2 != 0])

[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [20]:
odd[odd % 2 != 0] = -1
print(odd)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [21]:
arr = np.arange(10)
arr[[5,6,7,8]] = 12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [22]:
twoD = np.ones((4,4))
twoD[1:-1,1:-1] = 0
print(twoD)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [23]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6], 
                  [7, 8, 9]])
arr2d = np.where(arr2d == 5,12,arr2d)
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [24]:
arr3d = np.array([
    [
        [1, 2, 3], 
        [4, 5, 6]
    ], 
    [
        [7, 8, 9], 
        [10, 11, 12]
    ]
])
arr3d[0][0] = 64
print(arr3d)

[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [25]:
arr2d = np.arange(0,10).reshape((2,5))
print(arr2d)
arr2d[0]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [26]:
arr2d = np.arange(0,10).reshape((2,5))
print(arr2d)
arr2d[1][1]

[[0 1 2 3 4]
 [5 6 7 8 9]]


6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [27]:
arr2d = np.arange(0,10).reshape((2,5))
print(arr2d)
arr2d[:,2]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([2, 7])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [29]:
rand = np.random.randn((100)).reshape((10,10))
print(f"Minimun value {np.amin(rand)}")
print(f"Maximum value {np.amax(rand)}")

Minimun value -1.9603460947229845
Maximum value 2.46188325407753


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [31]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(f"Common elements : {np.intersect1d(a,b)}")

Common elements : [2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [32]:
np.searchsorted(a, np.intersect1d(a, b))

array([1, 5], dtype=int64)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [35]:
names = np.array(['John', 'Doe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data)
print('==================================================')
print(data[names != 'Will'])

[[ 0.94844877  0.52085949 -0.55053768 -1.83034492]
 [-0.30405341 -0.84660854  0.28039256 -0.28174196]
 [-0.61840277  1.0764557  -0.83543527  0.24873177]
 [ 2.73432063  1.48603024  1.32140258  1.75822095]
 [ 0.51616025 -0.06143259  0.11030803 -0.47600531]
 [ 0.38355345 -0.52672732  0.97159063 -1.0142188 ]
 [ 0.1399909  -0.27951106  1.26546619  0.07487705]]
[[ 0.94844877  0.52085949 -0.55053768 -1.83034492]
 [-0.30405341 -0.84660854  0.28039256 -0.28174196]
 [ 2.73432063  1.48603024  1.32140258  1.75822095]
 [ 0.38355345 -0.52672732  0.97159063 -1.0142188 ]
 [ 0.1399909  -0.27951106  1.26546619  0.07487705]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [36]:
print(data)
print('==================================================')
mask = (names != 'Will') & (names!= 'Joe')
print(data[mask])

[[ 0.94844877  0.52085949 -0.55053768 -1.83034492]
 [-0.30405341 -0.84660854  0.28039256 -0.28174196]
 [-0.61840277  1.0764557  -0.83543527  0.24873177]
 [ 2.73432063  1.48603024  1.32140258  1.75822095]
 [ 0.51616025 -0.06143259  0.11030803 -0.47600531]
 [ 0.38355345 -0.52672732  0.97159063 -1.0142188 ]
 [ 0.1399909  -0.27951106  1.26546619  0.07487705]]
[[ 0.94844877  0.52085949 -0.55053768 -1.83034492]
 [-0.30405341 -0.84660854  0.28039256 -0.28174196]
 [ 2.73432063  1.48603024  1.32140258  1.75822095]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [37]:
rand_arr = np.random.uniform(1,15, size=(5,3))
print(rand_arr)

[[11.47896607  2.24739055 11.02080014]
 [ 1.24373082 11.22848431  9.45754551]
 [14.39768635 12.62183649 12.43977534]
 [ 8.33525576  3.30448137  8.20321335]
 [11.52506862  9.83040038 13.73807473]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [38]:
rand_arr2 = np.random.uniform(1,16, size=(2,2,4))
print(rand_arr2)

[[[13.51256323  7.55691337  6.79378792  2.7085189 ]
  [ 7.25243578  6.54482483  1.0399747   3.20622163]]

 [[14.79740691 10.57850689  5.09934842  7.24032448]
  [ 5.60978879  7.96822773  5.79937208 14.75551896]]]


33. Swap axes of the array you created in Question 32

In [39]:
print("Original Array")
print(rand_arr2)
print("Swapped Axes")
print(np.swapaxes(rand_arr2, 2, 0))

Original Array
[[[13.51256323  7.55691337  6.79378792  2.7085189 ]
  [ 7.25243578  6.54482483  1.0399747   3.20622163]]

 [[14.79740691 10.57850689  5.09934842  7.24032448]
  [ 5.60978879  7.96822773  5.79937208 14.75551896]]]
Swapped Axes
[[[13.51256323 14.79740691]
  [ 7.25243578  5.60978879]]

 [[ 7.55691337 10.57850689]
  [ 6.54482483  7.96822773]]

 [[ 6.79378792  5.09934842]
  [ 1.0399747   5.79937208]]

 [[ 2.7085189   7.24032448]
  [ 3.20622163 14.75551896]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [40]:
arr = np.random.uniform(0,20, size=(10))
arr = arr.astype('int32') 
arr =np.sqrt(arr)
arr = np.where(arr < 0.5, 0, arr)
arr = arr.astype('int32')
print(arr)

[1 1 2 2 3 3 1 2 2 2]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [41]:
arr = np.random.uniform(0,20, size=(10))
arr1 = np.random.uniform(0,20, size=(10))
newArr = np.maximum(arr,arr1)
print(f"Array 1 : {arr}")
print(f"Array 2 : {arr1}")
print(f"New Array : {newArr}")

Array 1 : [18.82276288 10.89516224 12.66407119 16.01326158 14.60660058  7.23576348
  0.45646183 19.00160382 12.16750859  5.76827726]
Array 2 : [ 5.5172702  10.70764243 12.47656939 16.23707591  3.17110403 14.96653253
  6.62565435 15.962239    7.17698257  7.20294616]
New Array : [18.82276288 10.89516224 12.66407119 16.23707591 14.60660058 14.96653253
  6.62565435 19.00160382 12.16750859  7.20294616]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [42]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.sort(np.unique(names)))

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [43]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a, b)
print(c)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [44]:
sampleArray = np.array([
    [34,43,73],
    [82,22,12],
    [53,94,66]
])
newColumn = np.array([[10,10,10]])
sampleArray = np.delete(sampleArray, 2, axis=1)
sampleArray = np.insert(sampleArray, 2, newColumn, axis=1)
print(sampleArray)

[[34 43 10]
 [82 22 10]
 [53 94 10]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [45]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(np.dot(x,y))

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [46]:
ar = np.random.uniform(1,20,size=(4,5))
ar = ar.astype('int32')
print(ar.cumsum())

[ 18  22  38  54  58  64  67  81  82  96  99 113 120 139 140 154 172 175
 178 186]
